server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8083

# 서버 확인용 설정
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.17.0.2:3306/ajt?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: password
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#  session:
#    store-type: jdbc

# 로컬 확인용 설정
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 311241824711-iv9o8n2ut1up5fktgv6av6h6dqonnllc.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: S0EBiwRz_QEmUqrz8Zhz
            client-secret: hT5P847nFB
            scope:
            - name
            - email
            - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8083/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 리턴




logging:
  level:
    org.hibernate.SQL: debug
